name: My Workflow File

on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Print a greeting message
      - name: Print a greeting
        run: |
          echo "Hello there"

      # Step 3: Set up Python (you can specify the version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Set Python version (e.g., '3.9')]
      - run: python --version 

      # Step 4: Install dependencies (if you have a requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          #means that if there is a requirement file, it will know what library to install 
          #for this machine 
          #dependencies refer to external libraries or packages that your project needs 
          #in order to run. These are usually defined in a requirements.txt file for 
          #Python projects, which lists all the required packages and their specific versions.
