name: My Workflow File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Print a greeting message
      - name: Print a greeting
        run: |
          echo "Hello there"

      # Step 3: Set up Python (you can specify the version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Set Python version
      - run: python --version 

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      # Step 5: Run tests
      - name: Begin test
        run: |
          pytest
          
      # Step 6: Access the hidden repo
 #     - name: Hidden repo checkout 
  #      uses: actions/checkout@v4
   #     with:
    #      repository: sohliwen/UOBHidden
     #     path: hiddenfolder
      #    token: ${{ secrets.SECRETUOB }}

      # Step 7: Print out hidden files
     # - name: Print out hidden things 
        #run: |
    #      ls
      #    cd hiddenfolder
      #    ls

      # Step 8: Send a Discord notification
      - name: Discord notification 
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: The project {{ EVENT_PAYLOAD.repository.full_name }} is pending to be deployed.
 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ANOTHER_TOKEN }}
          publish_dir: ./  # Adjust if necessary to point to the directory containing index.html

      - if: ${{ success() }}
        name: discord 
        uses:  sebestianpopp/discord-action@releases/v2
        with:
          webhook: ${{  secrets.DISCORD_WEBHOOK }}
          message: The project {{ EVENT_PAYLOAD.repository.full_name }} is deployed. 

          
  
