
name: My Second Workflow File

on:
  pull_request:
    branches:
      - main

jobs:
  build2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Print a greeting message
      - name: Print a greeting
        run: |
          echo "Hello there"

      # Step 3: Set up Python (you can specify the version)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Set Python version (e.g., '3.9')]
      - run: python --version 

      # Step 4: Install dependencies (if you have a requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov
          

      - name: begin test
        run: |
          pytest -v -cov --junitxml=report.xml
          
     # this is where we acccess the hidden repo
      - name: Hidden repo checkout 
        uses: actions/checkout@v4
        with:
           repository: sohliwen/UOBHidden
           path: hiddenfolder
           token: ${{ secrets.SECRETUOB }}

    # this prints out the hidden files!
      - name: print out hidden things 
        run: |
          ls
          cd hiddenfolder
          ls

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
           files: |
             *.xml

       
   
